resolver: lts-12.6
packages:
- '.'

extra-deps:
- haskus-utils-1.0
- haskus-utils-types-1.0
- haskus-utils-data-1.0
- haskus-utils-variant-1.0
- haskus-binary-1.0

#allow-newer: true

flags:
   diagrams:
      rasterific: true

extra-package-dbs: []

ghc-options:
   "$locals": -fhide-source-paths
   "haskus-system": -fobject-code -freverse-errors
   # -fobject-code       -- GHCI needs it because of the foreign primops


compiler: ghc-8.4.3
ghc-variant: bugfix
# allow-newer: true

setup-info:
  ghc:
     linux64-custom-bugfix-tinfo6:
        8.4.3:
           url: "http://haskus.org/downloads/ghc-8.4.3-x86_64-bugfix-linux.tar.xz"
